# sonar-project.properties
sonar.projectKey=8to10_multi
sonar.projectName=8to10_multi
sonar.projectVersion=1.0

# Java 소스 경로 (src 기준)
sonar.sources=8to10_domain/src/main/java,8to10_api/src/main/java,8to10_db/src/main/java,8to10_security/src/main/java,8to10_scheduling/src/main/java
# 클래스(.class) 파일이 있는 경로 (gradle 빌드 기준)
sonar.java.binaries=8to10_domain/build/classes/java/main,8to10_api/build/classes/java/main,8to10_security/build/classes/java/main,8to10_scheduling/build/classes/java/main,8to10_db/build/classes/java/main

# 공통
sonar.language=java
sonar.sourceEncoding=UTF-8

# 서버 접속 정보
sonar.host.url=http://localhost:9000
sonar.login=squ_e3f00b399ab99cf30718e1425625c5888e2a8781