name: Deploy to CDN

on:
  push:
    branches:
      - main
    paths:
      - '8to10_frontend/**'

jobs:
  deploy:
    name: Deploy Frontend to CDN
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      

      - name: install npm dependencies
        run: npm install

      - name: Build React app
        working-directory: 8to10_frontend
        run: npm run build

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Upload to GCS
        run: |
          gsutil rsync -r 8to10_frontend/dist gs://$STATIC_ASSETS_BUCKET/
   
      - name: Invalidate CDN cache
        run: |
          gcloud compute url-maps invalidate-cdn-cache my-url-map \
            --path "/*"
